name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:ekioja2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
